export const GET_BANK_DETAILS_URL = "https://buddy-connect.encoreskydev.com/api/bank/getBankDetails.php?user_id=";
export const GET_PERSONAL_DETAILS_URL = "https://buddy-connect.encoreskydev.com/api/user/getPersonalDetail.php?id="
export const ADD_FAMILY_DETAILS_URL = "https://buddy-connect.encoreskydev.com/api/family/addFamilyDetail.php?user_id=";
export const GET_FAMILY_DETAILS_URL = "https://buddy-connect.encoreskydev.com/api/family/getFamilyDetails.php?user_id=";
export const DELETE_FAMILY_DETAILS_URL = "https://buddy-connect.encoreskydev.com/api/family/deleteFamilyDetail.php?user_id=";
export const DELETE_BANK_DETAILS_URL = "https://buddy-connect.encoreskydev.com/api/bank/deleteBankDetail.php?user_id="
export const ADD_SALARY_DETAILS_URL = "https://buddy-connect.encoreskydev.com/api/salary/addSalaryDetail.php?user_id="
export const GET_SALARY_DETAILS_URL = "https://buddy-connect.encoreskydev.com/api/salary/getSalaryDetails.php?user_id=";
export const SET_ACCOUNT_TYPE_URL = "https://buddy-connect.encoreskydev.com/api/bank/setAccountType.php?user_id=";
export const GET_USERS_URL = "https://buddy-connect.encoreskydev.com/api/user/users.php";
export const UPDATE_USER_DETAILS_URL = "https://buddy-connect.encoreskydev.com/api/user/updatePersonalDetail.php?id="
export const UPLOAD_USER_PROFILE_URL = "https://buddy-connect.encoreskydev.com/api/user/userImageUpload.php?id=";
export const DELTE_USER_URL = "https://buddy-connect.encoreskydev.com/api/user/deleteUser.php?user_id=";
export const IMAGE_SRC_URL = "https://buddy-connect.encoreskydev.com/upload/usersImage/";
export const DEFUALT_USER_AVATAR_URL = "https://d2ln1xbi067hum.cloudfront.net/assets/default_user-951af10295a22e5f7fa2fa6165613c14.png";
export const GET_FORMER_USERS_URL = "https://buddy-connect.encoreskydev.com/api/user/deletedUsers.php";
export const SET_USER_STATUS_URL = "https://buddy-connect.encoreskydev.com/api/user/userStatus.php?user_id=";